name: GoNetDisk
services:
  postgres:
    image: postgres:16-alpine
    container_name: GoNetDisk-postgres
    restart: always
    environment:
      POSTGRES_USER: GoNetDisk
      POSTGRES_PASSWORD: GoNetDisk
      POSTGRES_DB: GoNetDisk
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 500M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U GoNetDisk -d GoNetDisk"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: GoNetDisk-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    deploy:
      resources:
        limits:
          memory: 128M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: GoNetDisk-minio
    restart: always
    environment:
      MINIO_ROOT_USER: GoNetDisk
      MINIO_ROOT_PASSWORD: GoNetDisk
      TZ: Asia/Shanghai
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
      - ./minio_config:/root/.minio
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
