services:
  mysql:
    image: mysql:8.0
    container_name: gonetdisk-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gonetdisk
      MYSQL_DATABASE: gonetdisk
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z # 对应 2025-04-22 版本
    container_name: gonetdisk-minio
    restart: always
    environment:
      MINIO_ROOT_USER: gonetdisk # 建议修改为自定义用户名
      MINIO_ROOT_PASSWORD: gonetdisk # 建议修改为强密码
      TZ: Asia/Shanghai
    ports:
      - "9000:9000" # API 端口
      - "9001:9001" # Web Console 端口
    volumes:
      - ./minio_data:/data # 数据持久化目录
      - ./minio_config:/root/.minio # 配置文件目录
    command: server /data --console-address ":9001"
