server:
  port: 9090
  host: "0.0.0.0"
  mode: debug

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  accesskey: "GoNetDisk"
  secretkey: "GoNetDisk"
  bucket: "gonetdisk"
  usessl: false

database:
  host: "localhost"
  port: 5432
  user: "GoNetDisk"
  password: "GoNetDisk"
  name: "GoNetDisk"
  max_open_conns: 50
  max_idle_conns: 20
  conn_max_lifetime_min: 30
  conn_max_idle_time_min: 5

jwt:
  secret: "123321"
  accessexpiresmin: 1440
  refreshexpireshour: 168

upload:
  maxFileSizeMB: 100
