server:
  port: 9090
  host: "0.0.0.0"
  mode: debug

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "gonetdisk"
  name: "gonetdisk"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"

jwt:
  secret: "123321"
  expiresHours: 24

storage:
  tempDir: "./storage/temp"
  uploadDir: "./storage/uploads"

upload:
  maxFileSizeMB: 100